export const User = {
  // Read User Details
  GET_USER_DETAILS_BY_ID: "GET_USER_DETAILS_BY_ID",
  GET_USER_DETAILS_BY_ID_SUCCESS: "GET_USER_DETAILS_BY_ID_SUCCESS",
  GET_USER_DETAILS_BY_ID_FAILURE: "GET_USER_DETAILS_BY_ID_FAILURE",
  // clear user details
  CLEAR_USER_DETAILS: "CLEAR_USER_DETAILS",
};
